export const API_ROUTES = {
  langCodes: "https://devapi.hindustanvyapar.com/api/getSupportedLangs",
  // langCodes: '/lang-codes',
  // langStrings: 'https://devapi.hindustanvyapar.com/api/getLanguageLabels/en',
  langStrings: "/lang-strings",
  hsnCodes: "/hsn-codes",
  units: "/units",

  GET_NEW_ACCESS_TOKEN: "/getNewAccessToken",

  GET_OTP: "/getOTP",
  LOGIN: "/login",
  RE_LOGIN: "/relogin",
  CANCEL_RE_LOGIN: "/cancelrelogin",
  LOGOUT: "/logout",
  GET_LOGGEDIN_USER: "/getLoggedInUser",
  SAVE_DEVICE_TOKEN: "/saveUserDeviceToken",
  SAVE_USER_LOCATION: "/saveUserLocation",
  GET_USER_LIVE_LOCATION: "/getLiveLocation",
  GET_LOCATION_AND_USERS: "/getLocationsAndUsers",
  GET_ATTENDANCE_DETAILS: "/getUserAttendanceDetail",
  GET_ATTENDANCE_HISTORY: "/getUserAttendanceHistory",
  user: "/user",
  userProfile: "users/profile/me/",
  deleteUser: "/users/delete-user/",
  usersList: "/user/user-list",
  usersLocation: "/user/location",
  jwtRefresh: "/refresh-token",
  UPATE_CURRENT_PROFILE: "/updateCurrentProfile",

  product: "/products",
  productBaseData: "/products/base-data",
  vendorProduct: "/vendor/product/",
  superCatalogue: "/vendor/super-catalogue",
  deleteProduct: "/vendor/product/",
  updateProductSetting: "/vendor/productsetting/update/",

  vendor: "/vendors",
  vendorBaseData: "/vendors/base-data",
  vendorList: "/vendor/vendor/",
  companyProfle: "/vendor/company-profile/",
  vendorCustomer: "/vendor/customer/",
  customerLedger: "/vendor/customer/:id/ledger/",
  vendorLedger: "/vendor/vendor/:id/ledger/",
  vendorBank: "/vendor/get-bank/",
  vendorBankDetail: "/vendor/vendor-bank/",
  bankLedger: "/vendor/bank/:id/ledger/",
  vendorCash: "vendor/cash-balance/",
  // vendorCashLedger: "/vendor/cash-adjust-history/",
  vendorCashLedger: "/vendor/cash/ledger/",
  adjustCash: "vendor/cash-balance/adjust/",
  cashTransfer: "/vendor/cash-transfers/",
  bankToBankTransfer: "/vendor/bank-to-bank-transfers/",
  vendorAddBank: "vendor/vendor-bank/",
  vendorStores: "/vendor/vendor-stores/",

  getProductSettings: "/vendor/productsetting/",
  productSettings: "/vendor/productsetting/update/",
  smsSettings: "/vendor/sms-settings/",

  // Reminder settings
  reminderSettings: "/vendor/reminder-settings/",
  reminders: "vendor/reminders/",

  customer: "/customers",
  customerBaseData: "/customers/base-data",
  customerRequests: "/customer/requests/",
  deleteCustomerRequest: "/customer/requests/:id/",
  wholesaleRetailRequests: "vendor/request-list",
  createOffer: "/vendor/offer/",
  getOffers: "/customer/all-request-offer",
  getOffersById: "/customer/request-offer/",

  storeOnlineSetting: "/vendor/onlineStoreSetting/",
  automateNotificationOnOrder: "vendor/order-notification-message/",
  storeWorkingHour: "/vendor/store-working-hour/",
  storeWorkingHourBulk: "/vendor/store-working-hour/bulk/",

  posSales: "/vendor/sales/",
  posSalesInvoice: "vendor/customer-sale-invoice/",
  invoiceNumber: "/vendor/get-next-invoiceno/",

  GET_VENDOR_LIST: "/getAllVendors",

  purchaseNo: "/vendor/get-next-purchaseeno/",

  expenseCategory: "/masters/get-expense-category/",
  productCategory: "/masters/get-product-category/",
  productSubCategory: "/masters/get-product-subcategory/",
  expense: "vendor/expense/",

  paymnet: "/vendor/payments/",
  addons: "/vendor/addon/",
  spotlightProduct: "/vendor/spotlight-product/",
  deliveryBoys: "/vendor/deliveryboys/",
  deliveryBoysHistory: "/vendor/deliveryboys/manual-delivery-history/",
  autoDeliveryBoysHistory:
    "/vendor/deliveryboys/auto-assigned-delivery-history/",
  orders: "/vendor/orders/",
  ordersCancel: "/vendor/orders/:id/cancel-by-vendor/",
  orderItemTracking: "/vendor/order-item-tracking/",
  assignDeliveryBoy: "/vendor/orders/:id/assign-delivery-boy/",
  supportTickets: "/customer/support/tickets/",
  supportTicketMessages: "/customer/support/tickets/:ticket_id/messages/",
  printVariantChoices: "/vendor/print-variant/choices/",
  productSizes: "masters/get-size/",
  registerDeviceToken: "/users/register-device-token/",
  notificationCampaign: "/vendor/notifcation-campaign/",
  bannerCampaigns: "/vendor/banner-campaigns/",
  post: "/vendor/post/",
  reel: "/vendor/reel/",
  returnExchange: "/vendor/return-exchange/",
  storeReviews: "/vendor/store-reviews/",
  deliveryDiscount: "/vendor/delivery-discount/",
  purchase: "/vendor/purchase/",
  vendorDashboard: "/vendor/vendor-dashboard/dashboard",
  onlineOrderLedger: "/vendor/online-order-ledger/",
  topRatedProducts: "/vendor/top-rated-products/",
  activityFeed: "/vendor/activity-feed/",
};
